-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 19:14:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema technofit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `technofit` ;

-- -----------------------------------------------------
-- Schema technofit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technofit` DEFAULT CHARACTER SET utf8 ;
USE `technofit` ;

-- -----------------------------------------------------
-- Table `technofit`.`tipoatividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`tipoatividade` ;

CREATE TABLE IF NOT EXISTS `technofit`.`tipoatividade` (
  `idtipoAtividade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoAtividade`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `technofit`.`tipousuario` (
  `idtipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`instrutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`instrutor` ;

CREATE TABLE IF NOT EXISTS `technofit`.`instrutor` (
  `idinstrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `identidade` VARCHAR(12) NULL DEFAULT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  `tipoAtividade_idtipoAtividade` INT NOT NULL,
  PRIMARY KEY (`idinstrutor`),
  INDEX `fk_instrutor_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  INDEX `fk_instrutor_tipoAtividade1_idx` (`tipoAtividade_idtipoAtividade` ASC) VISIBLE,
  CONSTRAINT `fk_instrutor_tipoAtividade1`
    FOREIGN KEY (`tipoAtividade_idtipoAtividade`)
    REFERENCES `technofit`.`tipoatividade` (`idtipoAtividade`),
  CONSTRAINT `fk_instrutor_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipousuario` (`idtipoUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`aula` ;

CREATE TABLE IF NOT EXISTS `technofit`.`aula` (
  `idaula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `dataInicio` DATETIME NULL DEFAULT NULL,
  `horaFim` DATETIME NULL DEFAULT NULL,
  `diasDaSemana` VARCHAR(70) NULL DEFAULT NULL,
  `aulacol` VARCHAR(45) NULL DEFAULT NULL,
  `tipoAtividade_idtipoAtividade` INT NOT NULL,
  `instrutor_idinstrutor` INT NOT NULL,
  PRIMARY KEY (`idaula`),
  INDEX `fk_aula_tipoAtividade1_idx` (`tipoAtividade_idtipoAtividade` ASC) VISIBLE,
  INDEX `fk_aula_instrutor1_idx` (`instrutor_idinstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_aula_instrutor1`
    FOREIGN KEY (`instrutor_idinstrutor`)
    REFERENCES `technofit`.`instrutor` (`idinstrutor`),
  CONSTRAINT `fk_aula_tipoAtividade1`
    FOREIGN KEY (`tipoAtividade_idtipoAtividade`)
    REFERENCES `technofit`.`tipoatividade` (`idtipoAtividade`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`tipopresenca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`tipopresenca` ;

CREATE TABLE IF NOT EXISTS `technofit`.`tipopresenca` (
  `idtipoPresenca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipoPresenca`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`presenca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`presenca` ;

CREATE TABLE IF NOT EXISTS `technofit`.`presenca` (
  `idpresenca` INT NOT NULL AUTO_INCREMENT,
  `tipoPresenca_idtipoPresenca` INT NOT NULL,
  `aula_idaula` INT NOT NULL,
  PRIMARY KEY (`idpresenca`),
  INDEX `fk_presenca_tipoPresenca1_idx` (`tipoPresenca_idtipoPresenca` ASC) VISIBLE,
  INDEX `fk_presenca_aula1_idx` (`aula_idaula` ASC) VISIBLE,
  CONSTRAINT `fk_presenca_aula1`
    FOREIGN KEY (`aula_idaula`)
    REFERENCES `technofit`.`aula` (`idaula`),
  CONSTRAINT `fk_presenca_tipoPresenca1`
    FOREIGN KEY (`tipoPresenca_idtipoPresenca`)
    REFERENCES `technofit`.`tipopresenca` (`idtipoPresenca`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`tipoplano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`tipoplano` ;

CREATE TABLE IF NOT EXISTS `technofit`.`tipoplano` (
  `idtipoPlano` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoPlano`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`aluno` ;

CREATE TABLE IF NOT EXISTS `technofit`.`aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `identidade` VARCHAR(12) NOT NULL,
  `dataInscricao` DATE NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `valorMensalidade` DECIMAL(13,2) NOT NULL,
  `tipoPlano_idtipoPlano` INT NOT NULL,
  `presenca_idpresenca` INT NULL DEFAULT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT NULL,
  `diaPagamento` INT NULL DEFAULT NULL,
  `statuspagamento_idstatusPagamento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_aluno_tipoPlano_idx` (`tipoPlano_idtipoPlano` ASC) VISIBLE,
  INDEX `fk_aluno_presenca1_idx` (`presenca_idpresenca` ASC) VISIBLE,
  INDEX `fk_aluno_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_presenca1`
    FOREIGN KEY (`presenca_idpresenca`)
    REFERENCES `technofit`.`presenca` (`idpresenca`),
  CONSTRAINT `fk_aluno_tipoPlano`
    FOREIGN KEY (`tipoPlano_idtipoPlano`)
    REFERENCES `technofit`.`tipoplano` (`idtipoPlano`),
  CONSTRAINT `fk_aluno_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipousuario` (`idtipoUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 124
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`fisioterapeuta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`fisioterapeuta` ;

CREATE TABLE IF NOT EXISTS `technofit`.`fisioterapeuta` (
  `idfisioterapeuta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idfisioterapeuta`),
  INDEX `fk_fisioterapeuta_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_fisioterapeuta_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipousuario` (`idtipoUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`avaliacaofisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`avaliacaofisica` ;

CREATE TABLE IF NOT EXISTS `technofit`.`avaliacaofisica` (
  `idAvaliação` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `dataAvaliacao` DATE NULL DEFAULT NULL,
  `anamnese` VARCHAR(250) NULL DEFAULT NULL,
  `dobrasCutaneas` VARCHAR(250) NULL DEFAULT NULL,
  `ergonomico` VARCHAR(250) NULL DEFAULT NULL,
  `aluno_matricula` INT NOT NULL,
  `fisioterapeuta_idfisioterapeuta` INT NOT NULL,
  PRIMARY KEY (`idAvaliação`),
  INDEX `fk_avaliacaoFisica_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  INDEX `fk_avaliacaoFisica_fisioterapeuta1_idx` (`fisioterapeuta_idfisioterapeuta` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacaoFisica_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`),
  CONSTRAINT `fk_avaliacaoFisica_fisioterapeuta1`
    FOREIGN KEY (`fisioterapeuta_idfisioterapeuta`)
    REFERENCES `technofit`.`fisioterapeuta` (`idfisioterapeuta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`ferias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`ferias` ;

CREATE TABLE IF NOT EXISTS `technofit`.`ferias` (
  `idferias` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NULL DEFAULT NULL,
  `dataFim` DATE NULL DEFAULT NULL,
  `diasDisponiveis` INT NULL DEFAULT NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`idferias`),
  INDEX `fk_ferias_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_ferias_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `technofit`.`pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `dataPagamentoEfetuado` DATETIME NULL DEFAULT NULL,
  `valorPago` DECIMAL(13,2) NULL DEFAULT NULL,
  `aluno_matricula` INT NOT NULL,
  `dataPagamentoPrevisto` DATE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`))
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`sala` ;

CREATE TABLE IF NOT EXISTS `technofit`.`sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `aula_idaula` INT NOT NULL,
  PRIMARY KEY (`idSala`),
  INDEX `fk_Sala_aula1_idx` (`aula_idaula` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_aula1`
    FOREIGN KEY (`aula_idaula`)
    REFERENCES `technofit`.`aula` (`idaula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`statuspagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`statuspagamento` ;

CREATE TABLE IF NOT EXISTS `technofit`.`statuspagamento` (
  `idstatusPagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatusPagamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `technofit`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technofit`.`usuario` ;

CREATE TABLE IF NOT EXISTS `technofit`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(250) NOT NULL,
  `senha` VARCHAR(250) NULL DEFAULT NULL,
  `digital` BLOB NULL DEFAULT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipousuario` (`idtipoUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
