-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 18:17:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema technofit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technofit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technofit` DEFAULT CHARACTER SET utf8 ;
USE `technofit` ;

-- -----------------------------------------------------
-- Table `technofit`.`tipoPlano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`tipoPlano` (
  `idtipoPlano` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`tipoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`tipoPresenca` (
  `idtipoPresenca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipoPresenca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`tipoAtividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`tipoAtividade` (
  `idtipoAtividade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  PRIMARY KEY (`idtipoAtividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`tipoUsuario` (
  `idtipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`instrutor` (
  `idinstrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `cpf` VARCHAR(14) NULL,
  `identidade` VARCHAR(12) NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  `tipoAtividade_idtipoAtividade` INT NOT NULL,
  PRIMARY KEY (`idinstrutor`),
  INDEX `fk_instrutor_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  INDEX `fk_instrutor_tipoAtividade1_idx` (`tipoAtividade_idtipoAtividade` ASC) VISIBLE,
  CONSTRAINT `fk_instrutor_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrutor_tipoAtividade1`
    FOREIGN KEY (`tipoAtividade_idtipoAtividade`)
    REFERENCES `technofit`.`tipoAtividade` (`idtipoAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`aula` (
  `idaula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `dataInicio` DATETIME NULL,
  `horaFim` DATETIME NULL,
  `diasDaSemana` VARCHAR(70) NULL,
  `aulacol` VARCHAR(45) NULL,
  `tipoAtividade_idtipoAtividade` INT NOT NULL,
  `instrutor_idinstrutor` INT NOT NULL,
  PRIMARY KEY (`idaula`),
  INDEX `fk_aula_tipoAtividade1_idx` (`tipoAtividade_idtipoAtividade` ASC) VISIBLE,
  INDEX `fk_aula_instrutor1_idx` (`instrutor_idinstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_aula_tipoAtividade1`
    FOREIGN KEY (`tipoAtividade_idtipoAtividade`)
    REFERENCES `technofit`.`tipoAtividade` (`idtipoAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aula_instrutor1`
    FOREIGN KEY (`instrutor_idinstrutor`)
    REFERENCES `technofit`.`instrutor` (`idinstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`presenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`presenca` (
  `idpresenca` INT NOT NULL AUTO_INCREMENT,
  `tipoPresenca_idtipoPresenca` INT NOT NULL,
  `aula_idaula` INT NOT NULL,
  PRIMARY KEY (`idpresenca`),
  INDEX `fk_presenca_tipoPresenca1_idx` (`tipoPresenca_idtipoPresenca` ASC) VISIBLE,
  INDEX `fk_presenca_aula1_idx` (`aula_idaula` ASC) VISIBLE,
  CONSTRAINT `fk_presenca_tipoPresenca1`
    FOREIGN KEY (`tipoPresenca_idtipoPresenca`)
    REFERENCES `technofit`.`tipoPresenca` (`idtipoPresenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presenca_aula1`
    FOREIGN KEY (`aula_idaula`)
    REFERENCES `technofit`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `identidade` VARCHAR(12) NOT NULL,
  `dataInscricao` DATE NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(250) NULL,
  `telefone` VARCHAR(15) NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `dataPagamentoPrevisto` DATE NULL,
  `valorMensalidade` DECIMAL(13,2) NOT NULL,
  `tipoPlano_idtipoPlano` INT NOT NULL,
  `presenca_idpresenca` INT NOT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_aluno_tipoPlano_idx` (`tipoPlano_idtipoPlano` ASC) VISIBLE,
  INDEX `fk_aluno_presenca1_idx` (`presenca_idpresenca` ASC) VISIBLE,
  INDEX `fk_aluno_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_tipoPlano`
    FOREIGN KEY (`tipoPlano_idtipoPlano`)
    REFERENCES `technofit`.`tipoPlano` (`idtipoPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_presenca1`
    FOREIGN KEY (`presenca_idpresenca`)
    REFERENCES `technofit`.`presenca` (`idpresenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`statusPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`statusPagamento` (
  `idstatusPagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`idstatusPagamento`),
  INDEX `fk_statusPagamento_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_statusPagamento_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`fisioterapeuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`fisioterapeuta` (
  `idfisioterapeuta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idfisioterapeuta`),
  INDEX `fk_fisioterapeuta_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_fisioterapeuta_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`avaliacaoFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`avaliacaoFisica` (
  `idAvaliação` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `dataAvaliacao` DATE NULL,
  `anamnese` VARCHAR(250) NULL,
  `dobrasCutaneas` VARCHAR(250) NULL,
  `ergonomico` VARCHAR(250) NULL,
  `aluno_matricula` INT NOT NULL,
  `fisioterapeuta_idfisioterapeuta` INT NOT NULL,
  PRIMARY KEY (`idAvaliação`),
  INDEX `fk_avaliacaoFisica_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  INDEX `fk_avaliacaoFisica_fisioterapeuta1_idx` (`fisioterapeuta_idfisioterapeuta` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacaoFisica_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacaoFisica_fisioterapeuta1`
    FOREIGN KEY (`fisioterapeuta_idfisioterapeuta`)
    REFERENCES `technofit`.`fisioterapeuta` (`idfisioterapeuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`ferias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`ferias` (
  `idferias` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `diasDisponiveis` INT NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`idferias`),
  INDEX `fk_ferias_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_ferias_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`Sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `aula_idaula` INT NOT NULL,
  PRIMARY KEY (`idSala`),
  INDEX `fk_Sala_aula1_idx` (`aula_idaula` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_aula1`
    FOREIGN KEY (`aula_idaula`)
    REFERENCES `technofit`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(250) NOT NULL,
  `senha` VARCHAR(250) NULL,
  `digital` BLOB NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `technofit`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technofit`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technofit`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `dataPagamentoEfetuado` DATETIME NULL,
  `valorPago` DECIMAL(13,2) NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `technofit`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
